"""First rev

Revision ID: 10187e2579cb
Revises: None
Create Date: 2014-07-21 02:40:35.529083

"""

# revision identifiers, used by Alembic.
revision = '10187e2579cb'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_teams_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yearid', sa.Integer(), nullable=True),
    sa.Column('ncaaID', sa.String(length=140), nullable=True),
    sa.Column('statsheet', sa.String(length=140), nullable=True),
    sa.Column('ncaa', sa.String(length=140), nullable=True),
    sa.Column('espn_name', sa.String(length=140), nullable=True),
    sa.Column('espn', sa.String(length=140), nullable=True),
    sa.Column('cbs1', sa.String(length=140), nullable=True),
    sa.Column('cbs2', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['yearid'], ['raw_teams_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'users')
    op.add_column(u'game', sa.Column('yearid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'game', 'yearid')
    op.create_table(u'users',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column(u'name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column(u'email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column(u'role', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('raw_teams')
    op.drop_table('raw_teams_year')
    ### end Alembic commands ###
