"""add raw games relationship year

Revision ID: 26aa5861a130
Revises: 10187e2579cb
Create Date: 2014-07-22 03:53:21.736241

"""

# revision identifiers, used by Alembic.
revision = '26aa5861a130'
down_revision = '10187e2579cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
