"""change recipient column type

Revision ID: 2dbbfc59c83a
Revises: 26aa5861a130
Create Date: 2014-07-22 04:35:43.687891

"""

# revision identifiers, used by Alembic.
revision = '2dbbfc59c83a'
down_revision = '26aa5861a130'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
